### ISSUE TITLE
Web Workers not stripped of communication ability

### ISSUE THREAD

**Issue by willscott** [freedomjs/freedom#110]
Per https://github.com/uProxy/uproxy/issues/365

the code that needs to be added is probably at both:
https://github.com/freedomjs/freedom/blob/v0.6/src/moduleinternal.js#L57
for making sure the global object is overall cleaned
and
https://github.com/freedomjs/freedom/blob/v0.6/src/link/worker.js#L55
for webworker specific cleansing.

**Comment by soycode** [comment]
https://github.com/freedomjs/freedom/issues/136 is resolved so revisiting this.

**Comment by soycode** [comment]
Went back to my masking branch and merged up to the current state of freedom. Things seem to be mostly working (freedom demo apps run and unit tests pass with masking) with two caveats/todos:

-Debugging is now more painful because when you open Chrome console and try to switch to the freedom.js worker you get "Uncaught TypeError: Can't add property __commandLineAPI, object is not extensible" - in other words, Chrome seems to need to edit global scope at runtime to inspect/interact with webworker threads. If you don't use the console on the webworker thread then the error doesn't occur and the app runs fine, but as I said it makes debugging painful and I can't figure a good way to whitelist just this mutability without letting in the rest.

-A decent slate of integration tests still fail, mostly because they do things like create a temporary global variable to keep track of some test state. I'm hoping they're mostly refactorable in some sensible way and will push a few commits to that end in the near future, but we may have to add some more helper code/framework around integration testing at some point.

**Comment by soycode** [comment]
Spent some time debugging the loads-scripts-sequentially module test, and discovered that actually I still wasn't freezing the object at the right spot (it was freezing after each loaded script rather than all of them). Fixed that (https://github.com/freedomjs/freedom/commit/8641b91bcd6a952e8340ec7dd34554b04bb99b28) and now all integration tests pass (at least the first time I ran - on further runs one transport.webrtc.json test seems flaky but I don't think it's related).

The Chrome console issue is still a factor, and basically it's a problem because even just adding that property to the whitelist doesn't help (since the property isn't added to the object until after freedom is completely done loading). Ideally we'd say "let the browser mutate this one property but no others", but I don't think JavaScript provides that level of control here - so we may just want to add a "debug/dev" mode that allows for mutation in general. I'll look into a sensible way of doing that.

**Comment by soycode** [comment]
Status - what I want to do is add an e.g. if (!config.freezeScope)... around https://github.com/freedomjs/freedom/blob/soycode-webworker-masking/src/moduleinternal.js#L367 with the freezeScope parameter (default false) passed in optionally along with the manifest. Such parameters should get to moduleinternal (the webworker scope) via message.config at https://github.com/freedomjs/freedom/blob/soycode-webworker-masking/src/moduleinternal.js#L47 - however, after stepping through and logging a bunch it seems like what actually makes it that far is site_cfg which is set up at https://github.com/freedomjs/freedom/blob/soycode-webworker-masking/src/entry.js#L47 and does not include all the "external" config parameters.

The rub seems to be that the setup function which makes site_cfg does receive the external config, but only when it is making the site_cfg for the external scope. When it's setting up the webworker scope it's already lacking that parameter and so doesn't have the information to stick in site_cfg and pass on.

Anyway, I'll step through it more later but for now I wanted to (a) document my investigation for my own benefit at least, and (b) let you know in case I'm missing some more obvious way to pass config parameters to the webworker. site_cfg does indeed work and pass some parameters in, but it seems like it can't get them from the outermost scope, which is what I want.

**Comment by willscott** [comment]
At
https://github.com/freedomjs/freedom/blob/soycode-webworker-masking/src/entry.js#L62
just after the definition you link, site_cfg should get the additional
properties set by the page config added.

**Comment by ryscheng** [comment]
Out of curiosity, what properties does the Chrome debugger modify and for what reason?

**Comment by soycode** [comment]
Re: Will, yes but only when config is actually defined (and config is undefined when this is setting up webworkers, at least from my logging). For webworkers config seems undefined already by this point, so properties don't pass on.

Re: Ray, the error is "Uncaught TypeError: Can't add property __commandLineAPI, object is not extensible" - not sure the details, that exact error message doesn't give much on search but the specific __commandLineAPI gets results with people talking about various Chrome JavaScript dev issues. I'm assuming it needs to inject some property into the scope to give the nice interaction (ability to click through the hierarchy of any object, etc.).

**Comment by willscott** [comment]
soycode: 2 rounds of config we need to think about:

1st -> on the outer page the outer config should get mixed into site_cfg
and end up in the module's config.
2nd -> in the web worker, the external default site_cfg is around, but the
one in ModuleInternal should inherit from the external context due to:
https://github.com/freedomjs/freedom/blob/master/src/moduleinternal.js#L47

the config in link/worker within the worker doesn't get that now, though.

**Comment by ryscheng** [comment]
Is the only way to do this to freeze the global? Is there really no way to freeze WebSocket as undefined or null?
I would imagine there's a bunch of cases where we don't want to freeze global right?

**Comment by soycode** [comment]
With the whitelist we have to freeze the scope around it to prevent the potential of somebody deleting whatever masked object and causing it to be replaced with the regular browser primitive. It may be possible to switch to a blacklist approach and then just explicitly freeze those objects, but this would both be a somewhat different philosophy/design and also something with more potential for longterm maintenance (as new browser primitives come out etc.). I'm not necessarily opposed to it though, but would want to think through the costs/benefits some more.

Re: config, I've made a commit illustrating the points I'm trying to log at: https://github.com/freedomjs/freedom/commit/13c34120c39e9379f7bbbd9423a3883f01091f27

The "config" argument received by setup (line 38 entry.js) does have the outer page parameters and does mix things into site_cfg, but only on calls to setup that seem to lead to the setup of the outer scope. When setup is being called for the webworker that same argument is undefined, and while site_cfg still gets populated it seems like it's basically hardcoded - for instance, "debug" is always "log" for the webworker, even when I set it to be something else for the outer config.

**Comment by ryscheng** [comment]
Makes sense. Thanks for the clarification

**Comment by soycode** [comment]
Just want to put a summary note of this issue (from a long ago comment by Will in a pull request):

----------------------------------------
Sure. I guess the thing we need to insure is that you can't do 
```javascript 
delete WebSocket; 
var x = new WebSocket(); 
``` 
and have that work. It's the immutability of the outer DedicatedWorkerGlobalScope that needs to be ensured. We probably need to look at the semantics of importScripts as well, and see if it's possible for the imported script to run in a context we create that is mutable, rather than that locked down DedicatedWorkerGlobalScope. 

----------------------------------------
