### ISSUE TITLE
When providing an interface, the behavior of the internal "freedom" variable is inconsistent

### ISSUE THREAD

**Issue by ryscheng** [freedomjs/freedom#202]
For example in the chat demo, the root manifest provides "chat"
https://github.com/freedomjs/freedom/blob/master/demo/chat/manifest.json

Then when the provider is registered, we do a freedom().providePromises(Chat);
https://github.com/freedomjs/freedom/blob/master/demo/chat/main.js#L117

Contrast this with freedom-social-xmpp, which provides social
freedom.social().provideAsynchronous(XMPPSocialProvider);
https://github.com/freedomjs/freedom-social-xmpp/blob/master/src/core/socialprovider.js#L519

This means that when something as loaded as the root module, as opposed to a dependency, the behavior of freedom is different. When freedom-social-xmpp is loaded as a root module, 'freedom.social' is undefined and what we expect there is actually located at 'freedom'.

**Comment by ryscheng** [comment]
@dborkan thanks for helping me find this. We've added a temporary fix in freedom-social-xmpp until this gets resolved.

**Comment by willscott** [comment]
This is based on the presence or absence of the ```default``` key in the manifest.  chat has that, which promotes that API to ```freedom()```, while social-xmpp doesn't yet.

Solution here in the short-term is adding ```default: 'social'``` to the manifest here, and refactor socialProvider.js to say ```freedom().provideAsynchronous(...);```.  Then the tests will get the social interface.

Making this consistent so that the internal module environment doesn't change strangely based on manifest keys will come in 0.7, and is tracked in #204. Short term issue filed as https://github.com/freedomjs/freedom-social-xmpp/issues/82. That should resolve this more general issue.
