### ISSUE TITLE
Add core.jsonp interface/functionality

### ISSUE THREAD

**Issue by soycode** [freedomjs/freedom#224]
Needed to support e.g. Facebook login, and generally to allow cross-domain data/communication.

**Comment by soycode** [comment]
From a bit of reading around, it seems there is no real standard interface for JSONP. http://json-p.org/ advocates something like:
```
function handle_data(data) {
   // `data` is now the object representation of the JSON data
}


---
http://some.tld/web/service?callback=handle_data:
---
handle_data({"data_1": "hello world", "data_2": ["the","sun","is","shining"]});
```

And I do think that it is probably best for us to target (as default case) that:
- The JSONP "request" is a script tag loading some url w/callback parameter
- This callback parameter specifies a function name that "pads"/wraps actual JSON
- The included script doesn't do anything else

But strictly speaking, the included script is JavaScript and can do anything JavaScript can do, and could choose to just set some variables as a way to return data. Not sure if we want to/would be able to come up with ways to mitigate that, but worth noting.

**Comment by willscott** [comment]
There needs to be a `core.jsonp` interface because we want the script to load where the user Is (think about the for-cloud use case, where the worker is running on the server, and the UI is rendered in a browser. The 3rd party script should be loaded in the browser so that it has the user's credentials.)

The general way you would request this probably looks like:
```javascript
var url = 'http://3rdparty.com/script.js?callback=mycallback';
var request = freedom['core.jsonp']();
request.load(url, 'mycallback').then(function(data) {
  ...
});
```

You would pass the script to load and the callback you expect to be called. The only issue is that the callback could clobber other global handlers in the outside script, but the call can fail if that's in danger of happening.

**Comment by ryscheng** [comment]
I'd like to push back a bit until we know this is 100% necessary. See my comments here
https://github.com/freedomjs/freedom-social-firebase/issues/1

**Comment by soycode** [comment]
It is indeed <100% necessary.
